Added lint staged and added husky precommit script

diff --git a/code/.husky/pre-commit b/code/.husky/pre-commit
--- a/code/.husky/pre-commit
+++ b/code/.husky/pre-commit
@@ -1,2 +1,11 @@
-npm test
 echo "Running precommit hook..."
+
+cd code
+
+echo "Lint staged starting.."
+yarn lint-staged
+if [ $? -ne 0 ]; then
+    echo "Lint staged failed. Commit aborted."
+    exit 1
+fi
+echo "Lint staged successful"
